### ISSUE TITLE
Madmateでベントに入れない

### ISSUE THREAD

**Issue by lightsquall** [tomarai/tomarai.github.io#1]
作者様
いつも利用させていただいております。ありがとうございます。

[事象]
Evil Hackerで作ったMadmateは正常に動作するが、
ランダムで最初から選ばれる設定のMadmateはベントに入れない、タスクが表示される、等の動作不具合がある

[条件]
Steam Among Us v2021.11.9.5s
TOR + AUmod 3.2.4.1 利用時

[補足]
ホスト側で設定していても、他のメンバーに設定が反映されていない
（Madmate can enter VentがOnになっていても、他の参加者の画面はOffになっている）

**Comment by tomarai** [comment]
lightsquall さん
ご報告ありがとうございます。
条件から推測するに、`plugins` 以下に `TheOtherRoles.dll` と `AUMod.dll` が両方とも配置されているものと推測して以下の返事を行います。
まず、TheOtherRoles と AUMod の併用はお控えください。
（技術的なことを言うと TheOtherRoles と AUMod では Among Us のそれぞれの関数を hook するので、競合することによって動作が想定しないものとなります）
また、 EvilHacker が狂人を作成できる設定の場合、狂人の spawn rate に関わらず狂人は spawn しない仕様になっております。

**Comment by lightsquall** [comment]
お世話になっております。
ご回答ありがとうございます。

条件を詳しく記載しておらず、誠に申し訳ございません。

＞plugins 以下に TheOtherRoles.dll と AUMod.dll が両方とも配置されているものと推測して以下の返事を行います
こちらは、Aumod.dllのみです（参加者全員がそうだったかはちょっと不明です）

＞また、 EvilHacker が狂人を作成できる設定の場合、狂人の spawn rate に関わらず狂人は spawn しない仕様になっております。
ここも書き方が悪くて申し訳ございません
Evil Hackerが狂人を作れる設定はオフで、かつMadmateをONにしている（ランダムでMadmateが最初から選ばれる）
場合の話です。

お手数ですがご確認よろしくお願い致します。

**Comment by tomarai** [comment]
AUMod では EvilHacker は実装されていないので、 `AUMod.dll` のみでプレイされていたというご報告との一貫性が取れず、私としてはプレイ環境の再現が難しい状態です。

皆様で一度 plugins 以下の dll を確認してプレイすることをおすすめいたします。
こちら一度 close させて頂いて、また再発するようでしたら再度 issue を作っていただければと思います。
そのときには、設定画面、問題発生時のスクリーンショット等ありますと話が早くなる可能性があるかと存じます。
よろしくおねがいします。
