### ISSUE TITLE
MadmateのタスクがONの時にダウンロードアップロードタスクが複数発生する

### ISSUE THREAD

**Issue by lightsquall** [tomarai/tomarai.github.io#2]
作者様
いつも利用させていただいております。ありがとうございます。

[発生環境]
使用Ver：v3.3.3.1

[事象]
MadmateのタスクがONの時にダウンロードアップロードタスクが複数回発生する
ショート・コモン・ロングをそれぞれ1ずつにした際に複数ダウンロード・アップロードタスクが発生しています。

**Comment by tomarai** [comment]
ありがとうございます
この点に関しては私も把握済みなのですが、現状の実装ではナイーブに short, common, long からタスクをピックして割り当てるという処理をしているので厳密にはバグじゃないというように捉えています。
実際、Among Us において、複数のダウンロードタスクが設定されることが必ずないことを保証することは（ソースコード上をのぞいて）どこにもありません。
Among Us の現状の実装では同じ種類のタスクを設定しないようにするという処理が含まれているだけであって、ゲームのルールとしては存在していないという認識です。

プレイヤーの皆さまが複数発生しないほうが面白いと思っているのだろうなということは感じていますので、いずれ実装するかもしれませんが、現状あまり対応する気はないという感じです。
もちろんプルリクエストを送ってくだされば、コードレビューは行い、良い変更はマージいたします。

**Comment by lightsquall** [comment]
作者様

ご回答ありがとうございます。
そういうことなのですね、、、承知いたしました！
