### ISSUE TITLE
v3.4.2.1のDLLがアセットにAttachされていません

### ISSUE THREAD

**Issue by lightsquall** [tomarai/tomarai.github.io#3]
作者様
いつも利用させていただいております。ありがとうございます。

v3.4.2.1のDLLがアセットにAttachされていません
お手数ですがご確認をお願い致します。

**Comment by tomarai** [comment]
ありがとうございます

もう利用者がいないものだと思って、アップロードしていませんでした。
対応しておきました。

**Comment by lightsquall** [comment]
作者様
ご対応ありがとうございました！
